// js/mapping.js
export const teamNameMap = {
    // Premier League
    "Arsenal": "Arsenal FC",
    "Bournemouth": "AFC Bournemouth",
    "Brighton and Hove Albion": "Brighton & Hove Albion",
    "Burnley": "Burnley FC",
    "Chelsea": "Chelsea FC",
    "Everton": "Everton FC",
    "Fulham": "Fulham FC",
    "Liverpool": "Liverpool FC",
    "Sunderland": "Sunderland AFC",
    "Brentford": "Brentford FC",

    // La Liga
    "Alavés": "Deportivo Alavés",
    "Atlético Madrid": "Atlético de Madrid",
    "Barcelona": "FC Barcelona",
    "Celta Vigo": "Celta de Vigo",
    "Espanyol": "RCD Espanyol Barcelona",
    "Getafe": "Getafe CF",
    "Girona": "Girona FC",
    "Levante": "Levante UD",
    "Mallorca": "RCD Mallorca",
    "Osasuna": "CA Osasuna",
    "Real Betis": "Real Betis Balompié",
    "Sevilla": "Sevilla FC",
    "Valencia": "Valencia CF",
    "Villarreal": "Villarreal CF",
    "Oviedo": "Real Oviedo",

    // Serie A
    "Bologna": "Bologna FC 1909",
    "Cagliari": "Cagliari Calcio",
    "Como": "Como 1907",
    "Cremonese": "US Cremonese",
    "Fiorentina": "ACF Fiorentina",
    "Genoa": "Genoa CFC",
    "Juventus": "Juventus FC",
    "Lazio": "SS Lazio",
    "Milan": "AC Milan",
    "Napoli": "SSC Napoli",
    "Parma": "Parma Calcio 1913",
    "Pisa": "Pisa Sporting Club",
    "Roma": "AS Roma",
    "Sassuolo": "US Sassuolo",
    "Torino": "Torino FC",
    "Udinese": "Udinese Calcio",
    "Lecce": "US Lecce",

    // Bundesliga
    "1. FC Heidenheim": "1.FC Heidenheim 1846",
    "1. FC Köln": "1.FC Köln",
    "Augsburg": "FC Augsburg",
    "Bayer Leverkusen": "Bayer 04 Leverkusen",
    "Borussia Monchengladbach": "Borussia Mönchengladbach",
    "FSV Mainz 05": "1.FSV Mainz 05",
    "TSG Hoffenheim": "TSG 1899 Hoffenheim",
    "Union Berlin": "1.FC Union Berlin",
    "Werder Bremen": "SV Werder Bremen",

    // Ligue 1
    "Angers": "Angers SCO",
    "Auxerre": "AJ Auxerre",
    "Brest": "Stade Brestois 29",
    "Lille": "LOSC Lille",
    "Lorient": "FC Lorient",
    "Lyon": "Olympique Lyon",
    "Marseille": "Olympique Marseille",
    "Metz": "FC Metz",
    "Nantes": "FC Nantes",
    "Nice": "OGC Nice",
    "Paris Saint Germain": "Paris Saint-Germain",
    "Rennes": "Stade Rennais FC",
    "Strasbourg": "RC Strasbourg Alsace",
    "Toulouse": "FC Toulouse"
};